// <auto-generated />
namespace BlogMVCDeneme.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hataduzelt8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hataduzelt8));
        
        string IMigrationMetadata.Id
        {
            get { return "201705131927414_hataduzelt8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
